services:
  - type: web # Specifies this is a web service
    name: bgmi_frontend # Name of the service on Render
    env: node # Specifies the environment is Node.js
    region: oregon # Choose the region (e.g., oregon, frankfurt, etc.)
    branch: main # The branch in your Git repository to deploy
    repo: https://github.com/MdShamsherAlam/bgmi_frontendd.git # Replace with your repository URL
    buildCommand: npm install --production=false # Install dependencies, including dev dependencies
    startCommand: node app.js # Replace with the command to start your frontend server
    plan: free # Choose the pricing plan (free, starter, standard, etc.)
    autoDeploy: true # Automatically deploy on every commit to the branch
    envVars: # Environment variables for the application
      - key: NODE_ENV
        value: production
      - key: BASE_API_URL
        value: your-backend-api-url # URL of your backend API
      - key: SESSION_SECRET
        value: your-session-secret # Replace with your session secret for EJS and session handling
