services:
  - name: bgmi_frontend
    type: web
    env: node
    plan: free # Change to a paid plan if necessary
    buildCommand: npm install 
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Optional, Render assigns a default PORT dynamically
